name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Buildozer
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install --upgrade buildozer cython
          buildozer android debug
